### ISSUE TITLE
JAR doesn't start on MacOS

### ISSUE THREAD

**Issue by rstml** [danionita/e3tools#94]
```
% uname -a
Darwin rustam-mba.local 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64

% java -version
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

% java -jar e3tools-0.7.6.jar
no main manifest attribute, in e3tools-0.7.6.jar
```

**Comment by danionita** [comment]
Weird. The manifest attribute is present and I previously tested it on
MacOS.

Could you try running like this:
java -cp e3tools-0.7.6.jar design.Main

**Comment by rstml** [comment]
If I look into .jar, Main-class is not in the Manifest.

```
java -cp e3tools-0.7.6.jar design.Main

Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: com/mxgraph/view/mxGraph
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
	at java.lang.Class.getMethod0(Class.java:3018)
	at java.lang.Class.getMethod(Class.java:1784)
	at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
Caused by: java.lang.ClassNotFoundException: com.mxgraph.view.mxGraph
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 7 more
```

**Comment by danionita** [comment]
Ah, it seems I uploaded the wrong JAR to the latest release. I've replaced it with the right one.
Here is a direct link to it: https://github.com/danionita/e3tools/releases/download/v0.7.6/e3tools-0.7.7.jar

**Comment by rstml** [comment]
Works, thanks!
